name: coffee-classification-env
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pip
- pip:
  - mlflow==2.11.3
  - scikit-learn==1.3.2
  - pandas==2.1.3
  - numpy==1.24.4
  - matplotlib==3.8.2
  - seaborn==0.13.2
  - pyyaml==6.0.1

